### ISSUE TITLE
getting (java.lang.NoSuchMethodError) while trying to read rows in dataproc spark

### ISSUE THREAD

**Issue by abhinav719** [googleapis/java-bigtable#944]
hi
i am trying to read from bigtable from my spark job.
i am not building a fat jar, i am uploading the jars and running a dataproc job with --jars argument containing all the required jars.
I was getting class not found errors ,then i added all the required jars
However i am getting this error

java.lang.NoSuchMethodError: com.google.protobuf.Internal.checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
code snippet:

val dataClient = BigtableDataClient.create(projectId, instanceId)
 var query = Query.create(this.tablename)
val filters = FILTERS.chain()
filters.filter(FILTERS.qualifier().exactMatch(qualifier))
 dataClient.readRows(query.filter(filters))

stack trace:
: java.lang.NoSuchMethodError: com.google.protobuf.Internal.checkNotNull(Ljava/lang/Object;)Ljava/lang/Object;
        at com.google.protobuf.SingleFieldBuilderV3.<init>(SingleFieldBuilderV3.java:80)
        at com.google.bigtable.v2.ReadRowsRequest$Builder.getRowsFieldBuilder(ReadRowsRequest.java:1189)
        at com.google.bigtable.v2.ReadRowsRequest$Builder.getRowsBuilder(ReadRowsRequest.java:1151)
        at com.google.cloud.bigtable.data.v2.models.Query.rowKey(Query.java:84)
        at com.google.cloud.bigtable.data.v2.models.Query.rowKey(Query.java:78)
        at Services.BigtableService.$anonfun$getBatch$1(BigtableService.scala:51)
        at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:158)
        at Services.BigtableService.getBatch(BigtableService.scala:49)
        at v2.MobileTransformations$1.call(MobileTransformations.java:49)
        at v2.MobileTransformations$1.call(MobileTransformations.java:25)

i am not facing this issue while running code on local (normally ,not as a dataproc job)
i have checked the jar versions (on my local vs --jars on dataproc),they are exactly same.
don't know what can cause this
library version google-cloud-bigtable-1.27.2.jar

**Comment by abhinav719** [comment]
i also tried building a fat jar ,in that case i am getting a different error
: cannot find a NameResolver for bigtable.googleapis.com:443
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:764)
        at io.grpc.internal.ManagedChannelImpl.getNameResolver(ManagedChannelImpl.java:773)
        at io.grpc.internal.ManagedChannelImpl.<init>(ManagedChannelImpl.java:653)
        at io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:634)
        at io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:264)
        at io.grpc.ForwardingChannelBuilder.build(ForwardingChannelBuilder.java:258)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createSingleChannel(InstantiatingGrpcChannelProvider.java:360)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.access$1800(InstantiatingGrpcChannelProvider.java:81)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider$1.createSingleChannel(InstantiatingGrpcChannelProvider.java:231)
        at com.google.api.gax.grpc.ChannelPool.create(ChannelPool.java:72)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.createChannel(InstantiatingGrpcChannelProvider.java:241)
        at com.google.api.gax.grpc.InstantiatingGrpcChannelProvider.getTransportChannel(InstantiatingGrpcChannelProvider.java:219)
        at com.google.api.gax.rpc.ClientContext.create(ClientContext.java:199)
        at com.google.cloud.bigtable.data.v2.stub.EnhancedBigtableStub.create(EnhancedBigtableStub.java:143)
        at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:162)
        at com.google.cloud.bigtable.data.v2.BigtableDataClient.create(BigtableDataClient.java:154)

my build.sbt is

libraryDependencies ++= Seq(
    "org.scala-lang" % "scala-library" % "2.12.8",
    "org.apache.spark" %% "spark-core" % "3.1.1" ,
    "org.apache.spark" %% "spark-sql" % "3.1.1" ,
    "org.apache.spark" %% "spark-avro" % "3.1.1",
    "com.google.cloud.bigdataoss" % "gcs-connector" % "hadoop3-1.9.9" ,
    "com.google.cloud.spark" %% "spark-bigquery-with-dependencies" % "0.21.1",
    "com.googlecode.json-simple" % "json-simple" % "1.1",
    "com.google.cloud" % "google-cloud-bigtable" % "1.27.3",
    "mysql" % "mysql-connector-java" % "8.0.13",
)

assemblyMergeStrategy in assembly := {
    case PathList("META-INF", "MANIFEST.MF") => MergeStrategy.discard
    case x =>  MergeStrategy.first
}

**Comment by meredithslota** [comment]
Hi @abhinav719 — can you confirm which version of Dataproc you're using? There was an issue with dependency conflicts earlier with Dataproc 2.0.x vs Dataproc 1.5.x (internal issue 196964707 and 229419852 are some examples) that makes me think this is an issue with Dataproc, not with this library specifically. Is this issue persisting? https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-release-2.0 has a list of versions.

**Comment by abhinav719** [comment]
i am using 2.0x .I debugged it myself(it was 4 months ago), issue was with dataproc adding conflicting versions in the classpath. Solved it with shading the bigtable dependencies.
